"""Cummins EC-AGS+ fault codes, extracted from the app (FaultCode.generateFaultCodeMap).
code -> (name, description). Empty name = "Model specific fault. Refer to Operator Manual."
"""
FAULTS = {
    1: ('High Engine Temperature', 'Oil temperature exceeds high temperature limit threshold. Check for cooling air obstruction.'),
    2: ('Low Oil Pressure', 'Oil pressure below minimum operating level.'),
    3: ('Service Fault', 'Press the OFF/PRIME switch to activate two-digit fault.'),
    4: ('Over Crank', 'Engine did not start after 20 seconds of cranking. Check fuel level, wait two minutes & attempt restart.'),
    5: ('CO Detector Shutdown', 'Received external shutdown command.'),
    6: ('Low Oil Level', 'Oil level below minimum operating level.'),
    7: ('', 'Model specific fault. Refer to Operator Manual.'),
    8: ('', 'Model specific fault. Refer to Operator Manual.'),
    9: ('', 'Model specific fault. Refer to Operator Manual.'),
    11: ('', 'Model specific fault. Refer to Operator Manual.'),
    12: ('Output Over voltage', 'High output voltage detected.'),
    13: ('Output Under voltage', 'Low output voltage detected. Reduce number of connected loads.'),
    14: ('Output Over Frequency', 'High output frequency detected.'),
    15: ('Output Under Frequency', 'Low output frequency detected. Reduce number of connected loads.'),
    16: ('', 'Model specific fault. Refer to Operator Manual.'),
    17: ('Fuel Pump Circuit Fault', 'Fuel pump unresponsive.'),
    18: ('Glow Plug Circuit Fault', 'Glow plug unresponsive.'),
    19: ('Actuator Circuit Fault', 'Throttle actuator unresponsive.'),
    21: ('', 'Model specific fault. Refer to Operator Manual.'),
    22: ('', 'Model specific fault. Refer to Operator Manual.'),
    23: ('Oil Pressure Sensor Circuit Fault', 'Unable to determine oil pressure.'),
    24: ('Temperature Sensor Circuit Fault', 'Unable to determine temperature.'),
    25: ('Alternator Over Voltage', 'High internal system voltage detected.'),
    26: ('Alternator Under Voltage', 'Low internal system voltage detected.'),
    27: ('', 'Model specific fault. Refer to Operator Manual.'),
    28: ('DC Voltage Sense Lost', 'Unable to determine DC voltage.'),
    29: ('Battery Over Voltage', 'Battery voltage exceeds 17V.'),
    31: ('Engine Over Speed', 'High engine speed detected.'),
    32: ('Crank Under Speed', 'Low cranking speed detected. Check battery voltage & connections, verify proper oil viscosity for ambient temperature.'),
    33: ('', 'Model specific fault. Refer to Operator Manual.'),
    34: ('High Inverter Temperature', 'Internal inverter temperature exceeds high temperature limit threshold. Check for cooling air obstruciton.'),
    35: ('EE Checksum Fault', 'Controller firmware error.'),
    36: ('Mechanical Fault', 'Engine stopped without detected cause. Check generator fuel.'),
    37: ('Invalid Set Configuration', 'Incorrect software installed.'),
    38: ('Output Over Load', 'Output exeeded rated capacity of the generator. Reduce number of connected loads.'),
    39: ('Battery Under Voltage', 'Battery voltage below minimum operating level.'),
    41: ('Alternator Rotor Fault', 'Alternator rotor unresponsive.'),
    42: ('ROM Checksum Fault', 'Controller memory error.'),
    43: ('RAM Fault', 'Controller memory error.'),
    44: ('', 'Model specific fault. Refer to Operator Manual.'),
    45: ('Speed Sense Lost', 'Unable to determine engine speed.'),
    46: ('Output Over Current', 'High output current detected.'),
    47: ('Ignition Sense Lost', 'Unable to detect ignition.'),
    48: ('Field Sense Lost', 'Unable to determine field voltage.'),
    49: ('Actuator Over Load', 'Maximum engine throttle limit exceeded.'),
    51: ('Processor Fault', 'Controller processor error.'),
    52: ('Injector/Lift Pump Circuit Fault', 'Injector or lift pump unresponsive.'),
    53: ('Oil Temperature Sensor Circuit Fault', 'Unable to determine oil temperature.'),
    54: ('MAT Sensor Circuit Fault', 'Unable to determine Manifold Air Temperature.'),
    55: ('', 'Model specific fault. Refer to Operator Manual.'),
    56: ('MAP Sensor Circuit Fault', 'Unable to determine Manifold Air Pressure.'),
    57: ('Over Prime', 'Maximum fuel system priming time exceeded.'),
    58: ('High Exhaust Temperature', 'Exhaust temperature exceeds high temperature limit threshold.'),
    59: ('Low Coolant Level', 'Coolant level below minimum operating level.'),
    61: ('Emergency Shutdown', 'Received external shutdown command.'),
    62: ('', 'Model specific fault. Refer to Operator Manual.'),
    63: ('', 'Model specific fault. Refer to Operator Manual.'),
    64: ('', 'Model specific fault. Refer to Operator Manual.'),
    65: ('', 'Model specific fault. Refer to Operator Manual.'),
    66: ('', 'Model specific fault. Refer to Operator Manual.'),
    67: ('', 'Model specific fault. Refer to Operator Manual.'),
    68: ('', 'Model specific fault. Refer to Operator Manual.'),
    69: ('', 'Model specific fault. Refer to Operator Manual.'),
    71: ('', 'Model specific fault. Refer to Operator Manual.'),
    72: ('', 'Model specific fault. Refer to Operator Manual.'),
    73: ('', 'Model specific fault. Refer to Operator Manual.'),
    74: ('Unprogrammed Board', 'Controller missing system software.'),
    75: ('', 'Model specific fault. Refer to Operator Manual.'),
    76: ('Alternator Over Temperature', 'Alternator temperature exceeds high temperature limit threshold.'),
    77: ('', 'Model specific fault. Refer to Operator Manual.'),
    78: ('', 'Model specific fault. Refer to Operator Manual.'),
    79: ('', 'Model specific fault. Refer to Operator Manual.'),
    81: ('', 'Model specific fault. Refer to Operator Manual.'),
    82: ('', 'Model specific fault. Refer to Operator Manual.'),
    83: ('', 'Model specific fault. Refer to Operator Manual.'),
    84: ('', 'Model specific fault. Refer to Operator Manual.'),
    85: ('', 'Model specific fault. Refer to Operator Manual.'),
    86: ('', 'Model specific fault. Refer to Operator Manual.'),
    87: ('', 'Model specific fault. Refer to Operator Manual.'),
    88: ('', 'Model specific fault. Refer to Operator Manual.'),
    89: ('', 'Model specific fault. Refer to Operator Manual.'),
    91: ('', 'Model specific fault. Refer to Operator Manual.'),
    92: ('', 'Model specific fault. Refer to Operator Manual.'),
    93: ('', 'Model specific fault. Refer to Operator Manual.'),
    94: ('', 'Model specific fault. Refer to Operator Manual.'),
    95: ('', 'Model specific fault. Refer to Operator Manual.'),
    96: ('', 'Model specific fault. Refer to Operator Manual.'),
    97: ('', 'Model specific fault. Refer to Operator Manual.'),
    98: ('', 'Model specific fault. Refer to Operator Manual.'),
    99: ('', 'Model specific fault. Refer to Operator Manual.'),
}

def lookup(code):
    name, desc = FAULTS.get(code, ('', 'Unknown fault. Refer to Operator Manual.'))
    return {'code': code, 'name': name or 'Model-specific fault', 'description': desc}
